### PR TITLE
Logstash 5.x

### PR DESCRIPTION
**Pull request by juju4**
add option for repo between elastic 2.x or 5.x - latest requires java8
travis test include only for xenial as only one with java8 in official distribution

### CODE REVIEW

**Comment by geerlingguy** [comment]
I'd rather just go straight to 5.x, and update the test rigs to use Java 8 across the board. See https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tests/java-8.yml

**Comment by juju4** [comment]
Wouldn't not that defeat the interest of your java role to have that directly in other roles?
Else fine to switch 5.x as default or discard previous (might be more annoying for some)

**Comment by mgodlewski** [comment]
Merged in https://github.com/mgodlewski/ansible-role-logstash/pull/5

**Comment by geerlingguy** [comment]
I believe this has been fixed by a bit of a rewrite of the role (role version 4.0.0) to work with modern versions of logstash; see https://github.com/geerlingguy/ansible-role-logstash/commit/a1c342cc57c83d7ee8d1d87f340a11a7884b2405

Please re-open if you believe this issue is still relevant. Thanks!

**Pull request closed without merging**
