### PR TITLE
Update setup files to  be more dynamic

### PR DESCRIPTION
**Pull request by leifmadsen**
- use yum_repository module in Ansible 2.1
- drop static logstash.repo file
- add logstash_version to allow specific version installation

### CODE REVIEW

**Comment by leifmadsen** [comment]
Some of the syntax I've adjusted to not be single line, but full YAML as I ascribe to this philosophy: http://blog.bandwidth.com/why-you-should-use-yaml-as-yaml-with-ansible/

**Comment by geerlingguy** [comment]
So... in working on this role, I've already made a few of these changes through testing https://github.com/geerlingguy/ansible-vagrant-examples/issues/31 — but some others are not in the role yet (I don't think). Can you take a look at where we are now and resubmit? I like the ideas in this PR.

**Comment by mgodlewski** [comment]
Merged here: https://github.com/mgodlewski/ansible-role-logstash/pull/2

**Comment by leifmadsen** [comment]
Abandoned

**Pull request closed without merging**
