### PR TITLE
Upgrade Logstash to 2.x

### PR DESCRIPTION
**Pull request by asabirov**
Hello,

ElasticSearch 2.x is incompatible with LogStash 1.x. When use geerlingguy.elasticsearch it makes some headaches.

### CODE REVIEW

**Comment by mewm** [comment]
@asabirov you've only changed the repo for RedHat distributions. Line 9 in setup-Debian.yml should be changed to ```repo: 'deb http://packages.elasticsearch.org/logstash/2.3/debian stable main'```

**Comment by asabirov** [comment]
@mewm true, thanks

**Comment by geerlingguy** [comment]
Thanks so much! I've been meaning to do it myself... and now I don't have to :)

**Comment by geerlingguy** [comment]
I'll tag a new major version release for the role with the new major version of ES.

**Pull request merged**
